name: My Homepage Workflow  #workflow 이름
on:                         #해당 workflow가 언제 실행되는지 정의
  push:                     #push 이벤트 발생시 workflow 실행
    branches: ["main"]      #main branch에서 push 이벤트 발생시 workflow 실행
jobs:                       #workflow에서 진행할 하나 이상의 job들을 정의
  echo:                     #echo라는 식별자를 가진 job 정의
    runs-on: ubuntu-latest  #ubuntu-latest OS 환경에서 echo job 수행 
    steps:                  #아래로 step들을 정의
      - name: Welcome1      #step의 이름
        run: echo 'Welcome to my homepage!' #job에 할당된 ubuntu-latest 환경에서 echo 'Welcome to my homepage!'를 실행
  pwd:                      #pwd라는 식별자의 job 정의
    runs-on: ubuntu-latest  #ubuntu-latest OS 환경에서 pwd job 수행 
    steps:                  #아래로 step들을 정의
      - name: PWD           #step의 이름
        run: pwd            #job에 할당된 ubuntu-latest 환경에서 pwd를 실행
  build:                    #build라는 식별자를 가진 job 정의
    runs-on: ubuntu-latest  #ubuntu-latest OS 환경에서 build job 수행 
    env:                    #build job에서 사용할 변수
      VISIT_NUM: 'Minsu'    #build job에서 사용할 변수 VISIT_NUM 선언 및 정의
    steps:                  #아래로 step들을 정의 (step들이 순차적으로 실행됨)
      - uses: actions/checkout@v3 #깃허브에서 제공하는 action중 checkout action을 v3버전으로 사용(user: actions의 checkout repository를 v3로 참조하여 사용)

      - name: Install dependencies # step이름 정의
        run: |              #shell을 이용하여 command line 실행 (pip를 업데이트하고, pytest 설치)
          pip install --upgrade pip
          pip install ruff pytest
      - name: Greeting      #step 이름 정의
        run: |              #shell을 이용하여 command line 실행 (greeting.py를 테스트한다)
          pytest greeting.py


