name: My Homepage Workflow
on: 
  push:
    branches: ["main"]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome1
        run: echo 'Welcome to my homepage!'
  pwd:
    runs-on: ubuntu-latest
    steps: 
      - name: PWD
        run: pwd
  build:
    runs-on: ubuntu-latest
    env:
      VISIT_NUM: 'Minsu'
    
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
      - name: Greeting
        run: |
          pytest greeting.py


