name: My Homepage Workflow
on: 
  push:
    branches: ["main"]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome1
      - run: echo 'Welcome to my homepage!'

  build:
    runs-on: ubuntu-latest
    env:
      VISIT_NUM: 10
    
    steps:
      - name: Use actions repository
      - uses: actions/checkout@v3

      - name: Greeting
      - run: python greeting.py


